package securitywizards.herobo.com.androidtemplate.model.dataaccesslayer.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import securitywizards.herobo.com.androidtemplate.model.dataaccesslayer.greendao.Box;
import securitywizards.herobo.com.androidtemplate.model.dataaccesslayer.greendao.Student;

import securitywizards.herobo.com.androidtemplate.model.dataaccesslayer.greendao.BoxDao;
import securitywizards.herobo.com.androidtemplate.model.dataaccesslayer.greendao.StudentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig boxDaoConfig;
    private final DaoConfig studentDaoConfig;

    private final BoxDao boxDao;
    private final StudentDao studentDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        boxDaoConfig = daoConfigMap.get(BoxDao.class).clone();
        boxDaoConfig.initIdentityScope(type);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        boxDao = new BoxDao(boxDaoConfig, this);
        studentDao = new StudentDao(studentDaoConfig, this);

        registerDao(Box.class, boxDao);
        registerDao(Student.class, studentDao);
    }
    
    public void clear() {
        boxDaoConfig.getIdentityScope().clear();
        studentDaoConfig.getIdentityScope().clear();
    }

    public BoxDao getBoxDao() {
        return boxDao;
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

}
