package securitywizards.herobo.com.androidtemplate.model.dataaccesslayer.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table STUDENT.
 */
public class Student {

    private Long id;
    private String firstname;
    private String lastname;
    private String section;
    private String program;

    public Student() {
    }

    public Student(Long id) {
        this.id = id;
    }

    public Student(Long id, String firstname, String lastname, String section, String program) {
        this.id = id;
        this.firstname = firstname;
        this.lastname = lastname;
        this.section = section;
        this.program = program;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getSection() {
        return section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public String getProgram() {
        return program;
    }

    public void setProgram(String program) {
        this.program = program;
    }

}
